import 'package:flutter/material.dart';
import 'package:hospital_connect/core/theme/app_spacing.dart';
import 'package:hospital_connect/core/utils/formatters.dart';
import 'package:hospital_connect/models/models.dart';
import 'package:hospital_connect/services/slot_schedule_service.dart';
import 'package:hospital_connect/widgets/booking/date_selector_strip.dart';
import 'package:hospital_connect/widgets/booking/time_slot_grid.dart';

/// Interactive accessible date and time-slot selector component.
/// Displays working-hours slots generated by [SlotScheduleService].
class SlotSelector extends StatelessWidget {
  const SlotSelector({
    super.key,
    required this.doctor,
    required this.selectedDate,
    required this.selectedSlot,
    required this.onDateSelected,
    required this.onSlotSelected,
    this.existingAppointments = const [],
    this.scheduleService = const SlotScheduleService(),
    this.currentTime,
  });

  final DoctorModel doctor;
  final DateTime selectedDate;
  final String? selectedSlot;
  final ValueChanged<DateTime> onDateSelected;
  final ValueChanged<String> onSlotSelected;
  final List<AppointmentModel> existingAppointments;
  final SlotScheduleService scheduleService;
  final DateTime? currentTime;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;
    final now = currentTime ?? DateTime.now();
    final today = DateTime(now.year, now.month, now.day);

    // Next 14 days
    final days = List.generate(14, (i) => today.add(Duration(days: i)));

    // Generate slots from single source of truth
    final slots = scheduleService.getSlotsForDoctorAndDate(
      doctor: doctor,
      date: selectedDate,
      existingAppointments: existingAppointments,
      now: now,
    );

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Date Selector Header
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text(
              'Select Date',
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w700,
              ),
            ),
            Text(
              AppFormatters.formatDate(selectedDate),
              style: theme.textTheme.bodySmall?.copyWith(
                color: colorScheme.primary,
                fontWeight: FontWeight.w600,
              ),
            ),
          ],
        ),
        const SizedBox(height: AppSpacing.sm + 2),

        // Horizontal 14-day date picker cards
        DateSelectorStrip(
          days: days,
          selectedDate: selectedDate,
          today: today,
          onDateSelected: onDateSelected,
        ),
        const SizedBox(height: AppSpacing.xl),

        // Time Slot Grid & Legend
        TimeSlotGrid(
          slots: slots,
          selectedSlot: selectedSlot,
          onSlotSelected: onSlotSelected,
        ),
      ],
    );
  }
}
